### ISSUE TITLE
QR code presenting server address upon startup for better mobile development experience

### ISSUE THREAD

**Issue by tiagostutz** [lwsjs/lws#13]
Related issue: https://github.com/lwsjs/local-web-server/issues/148

**Comment by tiagostutz** [comment]
Small or Big?

<img width="913" alt="Captura de Tela 2020-05-08 às 15 56 22" src="https://user-images.githubusercontent.com/3986989/81439270-83026f80-9144-11ea-935d-a70048f7b823.png">

**Comment by 75lb** [comment]
small.. if the user has a 40x20 terminal window open, the large one won't fit..

**Comment by tiagostutz** [comment]
Currently, the behavior is as follows:
- If the user does not specify the `--qr` arg, we search for the most suitable private address to use to print the QRCode
- if the user specifies the `--qr` arg, we use it to print the QRCode

So, it will always present the QRCode. Maybe we should consider some changes in the args because as the default behavior now is to always print the QRCode, the args should be to hide or configure it. I mean, the user could pass a `--no-qr` arg to hide it and/or change the used interface using `--qr-address` (or something like) to specify the network interface.

or

we could keep to `--qr` using a convention like `--qr default` automatically choose the privately addressed network interface and if the user does not pass the  `--qr` param the QRCode won't be print.

What do you think?

**Comment by 75lb** [comment]
Hi, it should only print the QR code if the user asked for it. 

Regular behaviour: 

```
$ ws
```

Regular behaviour plus print a QR code with the default network interface:

```
$ ws --qr
```

or with a specific interface:
```
$ ws --qr en1
```

Does that sound ok?

**Comment by tiagostutz** [comment]
I tried this at first, but as the `—qr` is a String param, if there is no arg for it, it will not come in the config object and hence if the user won’t be able to pass only `—qr` and he/she will have to know the network interface...

Maybe `—qr auto` to leave the system automatically choose the network interface with private IP address could be an option.
Or is there a way to use `—qr` as String and Boolean flag at the same time?

**Comment by 75lb** [comment]
if `--qr` was specified, you should receive `qr: null` in the config object (you can can interpret `null` to mean "use the default interface").

If the `qr` property does not exist at all on the config object, then `--qr` was not set. Clear?

**Comment by 75lb** [comment]
The [documentation for the `type` property](https://github.com/75lb/command-line-args/blob/master/doc/option-definition.md#optiontype--function) in the option definition specifies that `null` is returned, if the option was set but no value was passed.. if this is not the case let me know.

**Comment by tiagostutz** [comment]
That's correct. I was making a wrong verification here.
Sorry about that.
Thanks!

**Comment by larryw3i** [comment]
Buddy, It could have been easier maybe!
