### ISSUE TITLE
Return non-zero exit code on cli-app crash

### ISSUE THREAD

**Issue by samthecodingman** [lwsjs/lws#6]
When the CLI module errors out, it simply logs it and then quits with a zero (success) exit code.

I propose adding `process.exitCode=1` to [`lws/lib/cli-app.js`](https://github.com/lwsjs/lws/blob/master/lib/cli-app.js) under [Line 25](https://github.com/lwsjs/lws/blob/master/lib/cli-app.js#L25).

If necessary, this can be behind a command line option such as `--use-exit-code` if worried about existing implementations.

**Comment by 75lb** [comment]
good point, I will look into it - thanks.

**Comment by 75lb** [comment]
fixed in lws@1.1.6.

Please reinstall or update local-web-server to pick up the change.
